accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('password/', views.password_change, name='password_change'),
    path('<int:account_pk>/profile/', views.profile, name='profile'),
    path('<int:account_pk>/follow/', views.follow, name='follow'),
    
    
]

crud/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('hashtags/<int:hashtag_pk>/', views.hashtag, name='hashtag'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# Create your models here.

class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings', blank=True)

articles/models.py
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill, ResizeToFit, Thumbnail
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings

# Create your models here.

class HashTag(models.Model):
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content




# 1. 모델(스키마) 정의
# 데이터베이스 테이블을 정의하고,
# 각각의 컬럼(필드) 정의
class Article(models.Model):
    # id : integer 자동으로 정의(Primary Key)
    # id = models.AutoField(primary_key=True) -> Integer 값이 자동으로 하나씩 증가(AUTOINCREMENT)
    # CharField - 필수인자로 max_length 지정
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = models.ImageField(blank=True)
    # ImageSpecField : Input 하나만 받고 잘라서 저장
    # ProcessedImageField : Input 받은 것을 처리해서 저장
    # resize to fill : 300*300
    # resize to fit : 긴쪽을(너비 혹은 높이) 300에 맞추고 비율에 맞게 자름
    image_thumbnail = ImageSpecField(
        processors=[ResizeToFit(300, 300)],
        format='JPEG',
        options={'quality': 80}
    )
    # DateTimeField
    #   auto_now_add : 생성시 자동으로 저장
    #   auto_now : 수정시마다 자동으로 저장
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)
    hashtags = models.ManyToManyField(HashTag, blank=True, related_name='articles')

    def __str__(self):
        return f'{self.id} : {self.title}'

class Comment(models.Model):
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # on_delete
    # 1. CASCADE : 글이 삭제되었을 때 모든 댓글을 삭제
    # 2. PROTECT : 댓글이 존재하면 글 삭제 안됨.
    # 3. SET_NULL : 글이 삭제되면 NULL로 치환(NOT NULL일 경우 옵션 사용X)
    # 4. SET_DEFAULT : 디폴트 값으로 치환.


# models.py : python 클래스 정의
#           : 모델 설계도
# makemigrations : migration 파일 생성
#                : DB 설계도 작성
# migrate : migration 파일 DB 반영

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', )

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email',)

accounts/views.py
from IPython import embed
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_GET
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth import get_user_model

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == 'POST':
        user_form = CustomUserCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        user_form = CustomUserCreationForm()
    context = {
        'user_form': user_form
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'Form': form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('articles:index')

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'Form': form
    }
    return render(request, 'accounts/update.html', context)

@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user) # 반드시 첫번째 인자로 user
    context = {
        'Form': form
    }
    return render(request, 'accounts/password_change.html', context)


def profile(request, account_pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=account_pk)
    context = {
        'user_profile': user
    }
    return render(request, 'accounts/profile.html', context)

def follow(request, account_pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=account_pk)
    if user != request.user:
        if request.user in user.followers.all():
            user.followers.remove(request.user)
        else:
            user.followers.add(request.user)
    return redirect('accounts:profile', account_pk)

accounts/templates/accounts/login.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}
{% block body %}
<form action="" method="POST" class="form">
  {% csrf_token %}
  {% bootstrap_form Form %}
  {% buttons %}
    <button type="submit" class="btn btn-outline-dark">Submit</button>
  {% endbuttons %}
  <a href="{% provider_login_url 'kakao' %}"> 카카오 로그인 </a>
  
</form>
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% block body %}
<form action="" method="POST" class="form" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form Form %}
  {% buttons %}
    <button type="submit" class="btn btn-outline-dark">Submit</button>
  {% endbuttons %}
</form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% block body %}

  <h1>{{ user_profile.username }}의 프로필 </h1>
  <br>
  {% with user_profile.followers.all as followers %}
  <span>팔로워 : {{followers|length}} | 팔로잉 : {{user_profile.followings.count}}</span>
  {% if user_profile != user %}
  <a href="{% url 'accounts:follow' user_profile.id %}" class="btn btn-outline-dark mb-2">
    {% if user in followers %}
      팔로우 취소
    {% else %}
      팔로우
    {% endif %}
  </a>
  {% endif %}
  <br>
  {% endwith%}
  {% if user == user_profile %}
  {% for article in user_profile.article_set.all %}
    <li>{{article.title}}</li>
  {% endfor %}
  <p>총 게시글 수 : {{user_profile.article_set.count}}</p>
  <hr>
  {% for comment in user_profile.comment_set.all %}
    <li>{{comment.content}}</li>
  {% endfor %}
  <p>총 댓글 수 : {{user_profile.comment_set.count}}</p>
  <hr>
  {% for like in user_profile.like_article %}
    <li>{{ like.title }</li>
  {% endfor %}
  <p>좋아요 한 수 : {{user_profile.like_article.count}}</p>
  <hr>
{% endif %}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% block body %}
<form action="" method="POST" class="form" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form user_form %}
  {% buttons %}
    <button type="submit" class="btn btn-outline-dark">Submit</button>
  {% endbuttons %}
</form>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% block body %}
<form action="" method="POST" class="form" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form Form %}
  {% buttons %}
    <button type="submit" class="btn btn-outline-dark">Submit</button>
  {% endbuttons %}
</form>
{% endblock %}