articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    # path('<int:article_pk>/edit/', views.edit, name='edit'),
    path('<int:article_pk>/update/', views.update, name='update'),
    # path('<int:comment_pk>/comment_delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
]

crud/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('hashtags/<int:hashtag_pk>/', views.hashtag, name='hashtag'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill, ResizeToFit, Thumbnail
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings

# Create your models here.

class HashTag(models.Model):
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content




# 1. 모델(스키마) 정의
# 데이터베이스 테이블을 정의하고,
# 각각의 컬럼(필드) 정의
class Article(models.Model):
    # id : integer 자동으로 정의(Primary Key)
    # id = models.AutoField(primary_key=True) -> Integer 값이 자동으로 하나씩 증가(AUTOINCREMENT)
    # CharField - 필수인자로 max_length 지정
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = models.ImageField(blank=True)
    # ImageSpecField : Input 하나만 받고 잘라서 저장
    # ProcessedImageField : Input 받은 것을 처리해서 저장
    # resize to fill : 300*300
    # resize to fit : 긴쪽을(너비 혹은 높이) 300에 맞추고 비율에 맞게 자름
    image_thumbnail = ImageSpecField(
        processors=[ResizeToFit(300, 300)],
        format='JPEG',
        options={'quality': 80}
    )
    # DateTimeField
    #   auto_now_add : 생성시 자동으로 저장
    #   auto_now : 수정시마다 자동으로 저장
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)
    hashtags = models.ManyToManyField(HashTag, blank=True, related_name='articles')

    def __str__(self):
        return f'{self.id} : {self.title}'

class Comment(models.Model):
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # on_delete
    # 1. CASCADE : 글이 삭제되었을 때 모든 댓글을 삭제
    # 2. PROTECT : 댓글이 존재하면 글 삭제 안됨.
    # 3. SET_NULL : 글이 삭제되면 NULL로 치환(NOT NULL일 경우 옵션 사용X)
    # 4. SET_DEFAULT : 디폴트 값으로 치환.


# models.py : python 클래스 정의
#           : 모델 설계도
# makemigrations : migration 파일 생성
#                : DB 설계도 작성
# migrate : migration 파일 DB 반영

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    # 위젯설정 2.
    title = forms.CharField(
        max_length=10,
        label='제목',
        widget=forms.TextInput(
            attrs={
                'placeholder': '제목을 입력바랍니다.'
            }
        )
    )
    class Meta:
        model = Article
        fields = ('title', 'content', 'image', )
        # fields = ('title', )
        # exclude = ('title', )
        # 위젯설정 1.
        # widgets = {
        #     'title': form.TextInput(
        #         attrs={
        #             'placeholder': '제목을 입력바랍니다.'
        #         }
        #     )
        # }

# class ArticleForm(forms.Form):
#     title = forms.CharField(
#         max_length=10,
#         label='제목',
#         widget=forms.TextInput(
#             attrs={
#                 'placeholder': '제목을 입력바랍니다.'
#             }
#         )
#     )
#     content = forms.CharField(
#         # label 내용 수정
#         label='내용',
#         # Django form에서 HTML 속성 지정 -> widget
#         widget=forms.Textarea(
#             attrs={
#                 'class': 'my-content',
#                 'placeholder': '내용을 입력바랍니다.',
#                 'rows': 5,
#                 'cols': 60
#             }
#         )
#     )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('article', 'user', )

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
# from IPython import embed
from django.views.decorators.http import require_POST, require_GET
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import ArticleForm, CommentForm
from .models import Article, Comment, HashTag
# from accounts.models import User
from django.contrib.auth import get_user_model
from django.conf import settings
from django.http import HttpResponseForbidden, HttpResponse

# Create your views here.
@require_GET
def index(request):
    articles = Article.objects.all()
    # embed()
    context = {
        'articles' : articles
    }
    # embed()
    return render(request, 'articles/index.html', context)

# def new(request):
#     if request.method == 'GET':
#         return render(request, 'articles/new.html')
#     else: #'POST'
#         new_title = request.POST.get('title')
#         new_content = request.POST.get('content')
#         article = Article(title=new_title, content=new_content)
#         article.save()
#         return redirect('articles:detail', article.pk )

@login_required
def create(request):
    # if request.user.is_authenticated:
    # 저장 로직
    if request.method == 'POST':
    # POST 요청 -> 검증 및 저장
        article_form = ArticleForm(request.POST, request.FILES)
        
        # embed()
        if article_form.is_valid():
        # 검증에 성공하면 저장하고,
            # new_title = article_form.cleaned_data.get('title')
            # new_content = article_form.cleaned_data.get('content')
            # article = Article(title=new_title, content=new_content)
            # article.save()
            article = article_form.save(commit=False)
            article.user = request.user
            article.save()
            for word in article.content.split():
                if word.startswith('#'):
                    hashtag, created = HashTag.objects.get_or_create(content=word)
                    article.hashtags.add(hashtag)

            # redirect
            return redirect('articles:detail', article.pk )
    else:
    # GET요청 -> Form
        article_form = ArticleForm()
    # GET -> 비어있는 Form context
    # POST -> 검증 실패시 에러메세지와 입력값 채워진 Form context
    context = {
        'article_form': article_form
    }
    return render(request, 'articles/form.html', context)
    # else:
    #     return redirect('accounts:login')

def detail(request, article_pk):
    # article = Article.objects.get(pk=article_pk)
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.comment_set.all()
    comment_form = CommentForm()
    context = {
        'article': article,
        'comments': comments,
        'comment_form': comment_form
    }
    return render(request, 'articles/detail.html', context)
    
@require_POST
def delete(request, article_pk):
    if request.user.is_authenticated:
        # article = Article.objects.get(pk=article_pk)
        article = get_object_or_404(Article, pk=article_pk)
        if article.user == request.user:
        # if request.method == "POST":
            article.delete()
            return redirect('articles:index')
        else:
            return HttpResponseForbidden()
    else:
        return HttpResponse('Unauthorized', status=401)

# def edit(request, article_pk):
#     if request.method == 'GET':
#         article = Article.objects.get(pk=article_pk)
#         context = {
#             'article': article
#         }
#         return render(request, 'articles/edit.html', context)
#     else:
#         article = Article.objects.get(pk=article_pk)
#         article.title = request.POST.get('title')
#         article.content = request.POST.get('content')
#         article.save()
#         return redirect('articles:detail', article.pk)

def update(request, article_pk):
    # article = Article.objects.get(pk=article_pk)
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.user:
        if request.method == 'POST':
            article_form = ArticleForm(request.POST, instance=article)
            # article = Article.objects.get(pk=article_pk)
            # article.title = request.POST.get('title')
            # article.content = request.POST.get('content')
            # article.save()
            if article_form.is_valid():
                article = article_form.save()
                # 해시태그 수정
                article.hashtags.clear()
                for word in article.content.split():
                    if word.startswith('#'):
                        hashtag, created = HashTag.objects.get_or_create(content=word)
                        article.hashtags.add(hashtag)
                return redirect('articles:detail', article.pk )
        else:
            article_form = ArticleForm(instance=article)
        context = {
            'article_form': article_form
        }
        return render(request, 'articles/form.html', context)
    else:
        return HttpResponseForbidden()

@require_POST
def comment_create(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        # 1. modelform에 사용자 입력값 넣고
        comment_form = CommentForm(request.POST)
        # 2. 검증하고,
        if comment_form.is_valid():
        # 3. 맞으면 저장!
        # 3-1. 사용자 입력값으로 comment instance 생성 (저장은 X)
            comment = comment_form.save(commit=False)
            # 3-2. FK 넣고 저장
            comment.article = article
            comment.user = request.user
            comment.save()
        # 4. return redirect
        else:
            messages.info(request, '댓글 형식이 맞지 않습니다.')
        return redirect('articles:detail', article_pk)
    else:
        return HttpResponse('Unauthorized', status=401)

    # comment = Comment()
    # comment.content = request.POST.get('content')
    # comment.article_id = article_pk
    # comment.save()
    # messages.info(request, '댓글이 등록되었습니다.')
    # return redirect('articles:detail', article_pk)

@require_POST
def comment_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
    # article_pk = comment.article_id
        comment.delete()
    # messages.error(request, '댓글이 삭제되었습니다.')
        messages.add_message(request, messages.INFO, '댓글이 삭제되었습니다.' )
        return redirect('articles:detail', article_pk)
    else:
        return HttpResponseForbidden()
from django.http import JsonResponse
@login_required
def like(request, article_pk):
    if request.is_ajax():
        article = get_object_or_404(Article, pk=article_pk)
        is_liked = True
        if request.user in article.like_users.all():
            article.like_users.remove(request.user)
            is_liked = False
        else:
            article.like_users.add(request.user)
            is_liked = True
        context = {
            'is_liked': is_liked,
            'like_count': article.like_users.count()}
        return JsonResponse(context)
    else:
        return HttpResponseForbidden()

def hashtag(request, hashtag_pk):
    hashtag = get_object_or_404(HashTag, pk=hashtag_pk)
    context = {
        'hashtag': hashtag
    }
    return render(request, 'articles/hashtag.html', context)

articles/templates/articles/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>게시판</title>
  <!--
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  -->
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
  <link rel="shortcut icon" href="{% static 'favicon/favicon.ico'%}" type="image/x-icon">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  {% block css %}{% endblock %}
</head>

<body>
  {% include '_navbar.html' %}
  <div class="container mt-5">
    {% block body %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}">
  </script>
  <script src="https://kit.fontawesome.com/54e342cbc4.js" crossorigin="anonymous"></script>
  {% block script %}
  {% endblock %}
</body>

</html>

articles/templates/articles/create.html
{% extends 'articles/base.html' %}
{% block body %}
  <h1>{{ article.id }} 번째 글이 작성되었습니다.</h1>
  <a href="{% url 'articles:index' %}">돌아가기</a>
{% endblock %}

articles/templates/articles/detail.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% block body %}
<h1>{{ article.id }}번 글</h1>
<h2>제목 : {{ article.title }}</h2>
<h2>작성자 : {{ article.user }}</h2>
<hr>
<div style="height: 200px">
  <p>{{ article.content|linebreaksbr }}</p>
  {% load hashtag %}
  <p>{{ article|make_link|safe|linebreaksbr }} </p>

</div>
  {% if article.image_thumbnail %}
    <img src="{{ article.image_thumbnail.url }}" alt="{{ article.image_thumbnail.name }}">
  {% endif %}
<br>
<hr>

<!-- <a href="{% url 'articles:like' article.pk %}"> -->
  {% if user in article.like_users.all %}
    <i id="like-button" data-id="{{article.id}}" class="fas fa-heart fa-2x" style="color:rgb(253, 76, 120)"></i>
    <!-- 좋아요취소 -->
  {% else %}
    <i id="like-button" data-id="{{article.id}}" class="far fa-heart fa-2x" style="color: rgb(253, 76, 120)"></i>
    <!-- 좋아요 -->
  {% endif %}
<!-- </a> -->
  <span id="like-count">{{ article.like_users.count }} 명이 이 글을 좋아합니다.</span>

<hr>
<p>작 성 일 : {{ article.created_at }}</p>
<p>최근 수정일 : {{ article.updated_at }}</p>
<a href="{% url 'articles:index'%}">목록으로</a>
{% if article.user == user %}
  <a href="{% url 'articles:update' article.pk %}">수정하기</a>
  <!-- <a href="{# url 'articles:delete' article.pk #}">삭제하기</a> -->
  <form action="{% url 'articles:delete' article.pk %}" method="POST" onclick="return confirm('진짜 지울래?')">
    {% csrf_token %}
    <input type="submit" value="삭제">
  </form>
{% endif %}
<hr>
<h3>댓글 작성</h3>

<form action="{% url 'articles:comment_create' article.pk %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form comment_form %}
  <input type="submit" value="얍~!">
</form>
<br>
<div>
  <p>댓글 보기</p>
  {% for comment in article.comment_set.all %}
    <li>{{ comment.user.username }} : {{ comment.content }} - {{ comment.created_at }}
        <!-- <a href="{# url 'articles:comment_delete' comment.pk #}">댓글삭제</a>  -->
    </li>
    {% if comment.user == user %}
        <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="POST" 
        onclick="return confirm('진짜 지울래?')">
            {% csrf_token %}
            <input type="submit" value="삭제">
        </form>
    {% endif %}
    {% empty %}
    <p> 댓글이 없어요ㅜㅜ 작성 해주세요</p>
    <br>
  {% endfor %}
  {% if messages %}
    <div class="messages text-info">
      {% for message in messages %}
        {{ message }}
      {% endfor %}
    </div>
  {% endif %}
</div>
<br>
{% endblock %}
{% block script %}
<script>
  const like = document.querySelector('#like-button')
  like.addEventListener('click', function(event) {
    // POST 요청 csrftoken을 AJAX 요청시 설정하는 법
    axios.defaults.xsrfCookieName = 'csrftoken'
    axios.defaults.xsrfHeaderName = 'X-CSRFToken'
    // django is_ajax() 분기가 되는 기준이 아래의 헤더 설정에 따라서 진행
    axios.defaults.headers.common['X-REQUESTED-WITH'] = 'XMLHttpRequest'
    axios.post(`/articles/${event.target.dataset.id}/like/`)
      .then(response => {
        if (response.data.is_liked) {
          event.target.classList.remove('far')
          event.target.classList.add('fas')
        }
        else{
          event.target.classList.remove('fas')
          event.target.classList.add('far')
        }
        const like_count = document.querySelector('#like-count')
        like_count.innerText = `${response.data.like_count} 명이 이 글을 좋아합니다.`
    })
    .catch(error => {
        console.log(error)
    })
  })
  
</script>

{% endblock %}

articles/templates/articles/edit.html
{% extends 'articles/base.html' %}
{% block body %}
<h1>글 수정하기</h1>
<br>
<form action="{% url 'articles:update' article.pk %}" method="POST">
  {% csrf_token %}
    {{ article_form.as_table }}
  <button type="submit" class="btn btn-outline-dark">Submit</button>
</form>
{% endblock %}

articles/templates/articles/edit2.html
{% extends 'articles/base.html' %}
{% block body %}
<h1>글 수정하기</h1>

<form action="{% url 'articles:update' article.pk %}" method="POST">
  {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">제목</label>
    <input name="title" value="{{article.title}}" type="text" class="form-control" id="exampleInputEmail1"
      aria-describedby="emailHelp">
    <small id="emailHelp" class="form-text text-muted">글의 제목을 작성해주세요.</small>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">내용</label>
    <textarea name="content" class="form-control" id="exampleFormControlTextarea1"
      rows="3">{{article.content}}</textarea>
  </div>
  <button type="submit" class="btn btn-outline-dark">게시글 수정</button>
</form>
{% endblock %}

articles/templates/articles/form.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% block body %}
{% if request.resolver_match.url_name == 'create' %}
  <h1 class="text-center">글 작성하기</h1>
{% else %}
  <h1 class="text-center">글 수정하기</h1>
{% endif %}
<br>
<form action="" method="POST" class="form" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form article_form %}
  {% buttons %}
    <button type="submit" class="btn btn-outline-dark">Submit</button>
  {% endbuttons %}
</form>
{% endblock %}

articles/templates/articles/hashtag.html
{% extends 'articles/base.html' %}
{% block body %}
<h1>{{ hashtag.content }}</h1>
{% for article in hashtag.articles.all %}
<a href="{% url 'articles:detail' article.pk %}">
  <p>{{article.title}}</p>
</a>
{% endfor %}
{% endblock %}

articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'articles/style.css' %}">
<style>
  tr > th:nth-of-type(2) {
    width: 50%;
  }
</style>
{% endblock %}
{% block body %}
<img src="{% static 'articles/bg.jpg'%}" alt="배경" width="500">
<h1 class="text-center my-5 title"> 게시판에 오신걸 환영합니다.</h1>
{% if user.is_authenticated %}
  <a href="{% url 'articles:create' %}" class="btn btn-outline-dark mb-2" style="float: right">글 작성하기</a>
{% endif%}

<table class="table mt-5">
    <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">제목</th>
      <th scope="col">작성일자</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}
    <tr>
      <th scope="row">
        {{ article.id }}</th>
      <td>
        {{ article.title }}
      </td>
      <td>{{ article.created_at }}</td>
      <td>
          <a href="{% url 'articles:detail' article.pk %}">글 보기</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

articles/templates/articles/new.html
{% extends 'articles/base.html' %}
{% block body %}
<h1 class="text-center">글 작성하기</h1>
<br>
<form action="" method="POST">
  {% csrf_token %}
  {{ article_form.as_p }}
  <label for="image">이미지 : </label>
  <input type="file" name="image" id="image">
  <button type="submit" class="btn btn-outline-dark">Submit</button>
</form>
{% endblock %}

articles/templates/articles/new2.html
{% extends 'articles/base.html' %}
{% block body %}
<h1 class="text-center">글 작성하기</h1>
<form action="{% url 'articles:create' %}" method="POST">
  {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">제목</label>
    <input name="title" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
      placeholder="제목을 입력하세요.">
    <small id="emailHelp" class="form-text text-muted">글의 제목을 작성해주세요.</small>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">내용</label>
    <textarea name="content" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>
  <input type="submit" class="btn btn-outline-dark" value="게시글 등록">
</form>
{% endblock %}